export const GET_PAIRED_DEVICES = "GET_PAIRED_DEVICES"
export const SET_PRINT_QUANTITY = 'SET_PRINT_QUANTITY'
export const RESET_PRINT_QUANTITY = 'RESET_PRINT_QUANTITY'
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM'
export const SET_CONNECTED_DEVICE = 'SET_CONNECTED_DEVICE'
